- docker/base/build.sh
- xgo.go
> allow using gomod

- docker/base/build.sh
I missed updating these when I changed gcc to use v6
> Update to use latest g++

- docker/base/Dockerfile
This will (hopefully) fix the recent build failures we have since #23
> WIP: Added xar

- xgo.go
- xgo_test.go
related issue [#41 ](https://github.com/techknowlogick/xgo/issues/41)
> fix: deal with image with a tag

- docker/base/Dockerfile
- docker/base/build.sh
Please review. Thank you,
--Ivan
Closes #45
> Enhancement: Support for s390x and ppc64le

- xgo.go
> pass goproxy env var

- xgo.go
Credit to @bcvery1 on PR#119 from original repo
> Modified paths to work with Windows

- docker/base/build.sh
source: https://monkeywie.github.io/2019/10/10/go-cross-compile/
> go modules fix

- docker/base/build.sh
> set owner of created executables to owner of the /build direcotry

- .github/workflows/build_images.yml
- .github/workflows/test_pr.yml
- docker/base/Dockerfile
- docker/base/bootstrap_pure.sh
- docker/base/build.sh
- xgo.bats
> xgo 1.16 darwin/amd64 - increase base sdk version

- xgo.go
In order to support using the users ssh key to access private git repos
> Added option to enable ssh agent forwarding

- README.md
- docker/base/build.sh
- xgo.go
> Support -gcflags flag

- docker/base/Dockerfile
Fixes: https://github.com/techknowlogick/xgo/issues/154
> add git safe.directory

- README.md
> WIP: Mention WoodpeckerCI in Readme

- README.md
- docker/base/Dockerfile
- docker/base/bootstrap_pure.sh
- docker/base/build.sh
> Add linux/riscv64 support

- .github/workflows/test_pr.yml
- docker/base/build.sh
There was a bug in #180 whereby quoting was messed up - this PR correctly uses arrays to fix this
Fix #182
Signed-off-by: Andrew Thornton <art27@cantab.net>
> Fix broken build

- docker/base/build.sh
- xgo.go
There was an unfortunate misunderstanding in #180 which did not properly take account of how xgo.go handled remote builds as compared to local builds, and modules.
This PR adjusts the way `xgo` handles `GO111MODULE` and the way it sets `GO111MODULE` to more closely match the way go 1.16+ handles `GO111MODULE` - and it makes remote builds work again (albeit there is a problem here, see below...)
From go1.16 module aware builds are assumed by default with `GO111MODULE`. This means `GO111MODULE=""` means `GO111MODULE="on"`.  This differs from the previous state where `GO111MODULE=""` meant `GO111MODULE="auto"`.
`xgo` will now respect the `GO111MODULE` environment variable in the context it run in. If it is empty, a module aware build is performed by default. If it is `"auto"` `xgo` will …
> Ensure modules are correctly handled including remote modules

- README.md
- docker/build/build.sh
- xgo.go
this allows to execute arbitrary command. first in a setup phase and
later in the loop over all targets.
the scripts are source to have access on all variables.
fixes: #96
> call userprovided setup.sh and build.sh script if existing

- docker/build/build.sh
- docker/toolchain/Dockerfile
- docker/toolchain/bootstrap_pure.sh
Fix https://github.com/techknowlogick/xgo/issues/163
> Bump to Ubuntu 20.04

- docker/build/build.sh
- xgo.go
Allow specifying -buildvcs= go build option
> Allow specifying -buildvcs= go build option
